//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeWeb.Comunicacion {
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service")]
    public partial class ServicioComunicacionIOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IOException iOExceptionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public IOException IOException {
            get {
                return this.iOExceptionField;
            }
            set {
                this.iOExceptionField = value;
                this.RaisePropertyChanged("IOException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://io.java/xsd")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service", ConfigurationName="Comunicacion.ServicioComunicacionPortType")]
    public interface ServicioComunicacionPortType {
        
        // CODEGEN: El parámetro 'usuarioJson' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:UpdateCuentaUsuario", ReplyAction="urn:UpdateCuentaUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafeWeb.Comunicacion.ServicioComunicacionIOException), Action="urn:UpdateCuentaUsuarioServicioComunicacionIOException", Name="ServicioComunicacionIOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SafeWeb.Comunicacion.UpdateCuentaUsuarioResponse UpdateCuentaUsuario(SafeWeb.Comunicacion.UpdateCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UpdateCuentaUsuario", ReplyAction="urn:UpdateCuentaUsuarioResponse")]
        System.Threading.Tasks.Task<SafeWeb.Comunicacion.UpdateCuentaUsuarioResponse> UpdateCuentaUsuarioAsync(SafeWeb.Comunicacion.UpdateCuentaUsuarioRequest request);
        
        // CODEGEN: El parámetro 'usuarioJson' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:InsertCuentaUsuario", ReplyAction="urn:InsertCuentaUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafeWeb.Comunicacion.ServicioComunicacionIOException), Action="urn:InsertCuentaUsuarioServicioComunicacionIOException", Name="ServicioComunicacionIOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SafeWeb.Comunicacion.InsertCuentaUsuarioResponse InsertCuentaUsuario(SafeWeb.Comunicacion.InsertCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:InsertCuentaUsuario", ReplyAction="urn:InsertCuentaUsuarioResponse")]
        System.Threading.Tasks.Task<SafeWeb.Comunicacion.InsertCuentaUsuarioResponse> InsertCuentaUsuarioAsync(SafeWeb.Comunicacion.InsertCuentaUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ValidarUsuario", ReplyAction="urn:ValidarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SafeWeb.Comunicacion.ServicioComunicacionIOException), Action="urn:ValidarUsuarioServicioComunicacionIOException", Name="ServicioComunicacionIOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SafeWeb.Comunicacion.ValidarUsuarioResponse ValidarUsuario(SafeWeb.Comunicacion.ValidarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ValidarUsuario", ReplyAction="urn:ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<SafeWeb.Comunicacion.ValidarUsuarioResponse> ValidarUsuarioAsync(SafeWeb.Comunicacion.ValidarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCuentaUsuario", WrapperNamespace="http://service", IsWrapped=true)]
    public partial class UpdateCuentaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuarioJson;
        
        public UpdateCuentaUsuarioRequest() {
        }
        
        public UpdateCuentaUsuarioRequest(string usuarioJson) {
            this.usuarioJson = usuarioJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCuentaUsuarioResponse", WrapperNamespace="http://service", IsWrapped=true)]
    public partial class UpdateCuentaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service", Order=0)]
        public int @return;
        
        public UpdateCuentaUsuarioResponse() {
        }
        
        public UpdateCuentaUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertCuentaUsuario", WrapperNamespace="http://service", IsWrapped=true)]
    public partial class InsertCuentaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuarioJson;
        
        public InsertCuentaUsuarioRequest() {
        }
        
        public InsertCuentaUsuarioRequest(string usuarioJson) {
            this.usuarioJson = usuarioJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertCuentaUsuarioResponse", WrapperNamespace="http://service", IsWrapped=true)]
    public partial class InsertCuentaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service", Order=0)]
        public bool @return;
        
        public InsertCuentaUsuarioResponse() {
        }
        
        public InsertCuentaUsuarioResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarUsuario", WrapperNamespace="http://service", IsWrapped=true)]
    public partial class ValidarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuarioJson;
        
        public ValidarUsuarioRequest() {
        }
        
        public ValidarUsuarioRequest(string usuarioJson) {
            this.usuarioJson = usuarioJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarUsuarioResponse", WrapperNamespace="http://service", IsWrapped=true)]
    public partial class ValidarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public ValidarUsuarioResponse() {
        }
        
        public ValidarUsuarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioComunicacionPortTypeChannel : SafeWeb.Comunicacion.ServicioComunicacionPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioComunicacionPortTypeClient : System.ServiceModel.ClientBase<SafeWeb.Comunicacion.ServicioComunicacionPortType>, SafeWeb.Comunicacion.ServicioComunicacionPortType {
        
        public ServicioComunicacionPortTypeClient() {
        }
        
        public ServicioComunicacionPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioComunicacionPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioComunicacionPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioComunicacionPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafeWeb.Comunicacion.UpdateCuentaUsuarioResponse SafeWeb.Comunicacion.ServicioComunicacionPortType.UpdateCuentaUsuario(SafeWeb.Comunicacion.UpdateCuentaUsuarioRequest request) {
            return base.Channel.UpdateCuentaUsuario(request);
        }
        
        public int UpdateCuentaUsuario(string usuarioJson) {
            SafeWeb.Comunicacion.UpdateCuentaUsuarioRequest inValue = new SafeWeb.Comunicacion.UpdateCuentaUsuarioRequest();
            inValue.usuarioJson = usuarioJson;
            SafeWeb.Comunicacion.UpdateCuentaUsuarioResponse retVal = ((SafeWeb.Comunicacion.ServicioComunicacionPortType)(this)).UpdateCuentaUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafeWeb.Comunicacion.UpdateCuentaUsuarioResponse> SafeWeb.Comunicacion.ServicioComunicacionPortType.UpdateCuentaUsuarioAsync(SafeWeb.Comunicacion.UpdateCuentaUsuarioRequest request) {
            return base.Channel.UpdateCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafeWeb.Comunicacion.UpdateCuentaUsuarioResponse> UpdateCuentaUsuarioAsync(string usuarioJson) {
            SafeWeb.Comunicacion.UpdateCuentaUsuarioRequest inValue = new SafeWeb.Comunicacion.UpdateCuentaUsuarioRequest();
            inValue.usuarioJson = usuarioJson;
            return ((SafeWeb.Comunicacion.ServicioComunicacionPortType)(this)).UpdateCuentaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafeWeb.Comunicacion.InsertCuentaUsuarioResponse SafeWeb.Comunicacion.ServicioComunicacionPortType.InsertCuentaUsuario(SafeWeb.Comunicacion.InsertCuentaUsuarioRequest request) {
            return base.Channel.InsertCuentaUsuario(request);
        }
        
        public bool InsertCuentaUsuario(string usuarioJson) {
            SafeWeb.Comunicacion.InsertCuentaUsuarioRequest inValue = new SafeWeb.Comunicacion.InsertCuentaUsuarioRequest();
            inValue.usuarioJson = usuarioJson;
            SafeWeb.Comunicacion.InsertCuentaUsuarioResponse retVal = ((SafeWeb.Comunicacion.ServicioComunicacionPortType)(this)).InsertCuentaUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafeWeb.Comunicacion.InsertCuentaUsuarioResponse> SafeWeb.Comunicacion.ServicioComunicacionPortType.InsertCuentaUsuarioAsync(SafeWeb.Comunicacion.InsertCuentaUsuarioRequest request) {
            return base.Channel.InsertCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafeWeb.Comunicacion.InsertCuentaUsuarioResponse> InsertCuentaUsuarioAsync(string usuarioJson) {
            SafeWeb.Comunicacion.InsertCuentaUsuarioRequest inValue = new SafeWeb.Comunicacion.InsertCuentaUsuarioRequest();
            inValue.usuarioJson = usuarioJson;
            return ((SafeWeb.Comunicacion.ServicioComunicacionPortType)(this)).InsertCuentaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SafeWeb.Comunicacion.ValidarUsuarioResponse SafeWeb.Comunicacion.ServicioComunicacionPortType.ValidarUsuario(SafeWeb.Comunicacion.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuario(request);
        }
        
        public string ValidarUsuario(string usuarioJson) {
            SafeWeb.Comunicacion.ValidarUsuarioRequest inValue = new SafeWeb.Comunicacion.ValidarUsuarioRequest();
            inValue.usuarioJson = usuarioJson;
            SafeWeb.Comunicacion.ValidarUsuarioResponse retVal = ((SafeWeb.Comunicacion.ServicioComunicacionPortType)(this)).ValidarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SafeWeb.Comunicacion.ValidarUsuarioResponse> SafeWeb.Comunicacion.ServicioComunicacionPortType.ValidarUsuarioAsync(SafeWeb.Comunicacion.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SafeWeb.Comunicacion.ValidarUsuarioResponse> ValidarUsuarioAsync(string usuarioJson) {
            SafeWeb.Comunicacion.ValidarUsuarioRequest inValue = new SafeWeb.Comunicacion.ValidarUsuarioRequest();
            inValue.usuarioJson = usuarioJson;
            return ((SafeWeb.Comunicacion.ServicioComunicacionPortType)(this)).ValidarUsuarioAsync(inValue);
        }
    }
}
